# Generated by Django 4.2.28 on 2026-03-02 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eclass',
            name='announcement',
        ),
    ]
