# Generated by Django 4.2.28 on 2026-03-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_eclass_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eclass',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='classes', to='index.subject'),
        ),
    ]
