# Generated by Django 4.2.28 on 2026-03-12 07:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_eclass_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='major',
        ),
        migrations.AddField(
            model_name='exercise',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Time limit in minutes', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.BooleanField(default=False, help_text='True = Multiple Choice, False = Short Answer'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='major_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.subject'),
        ),
    ]
