# Generated by Django 4.2.28 on 2026-03-12 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_exercise_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='eclass',
            name='main_teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_teacher', to='index.teacher'),
        ),
    ]
