# Generated by Django 4.2.28 on 2026-03-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_eclass_main_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questions',
            new_name='description',
        ),
    ]
