# Generated by Django 4.2.28 on 2026-03-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_rename_questions_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.subject'),
        ),
    ]
